"""init schema

Revision ID: 23d64303c67a
Revises:
Create Date: 2026-01-11 02:04:25.622205

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23d64303c67a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venues_slug"), "venues", ["slug"], unique=True)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("price_text", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_external_id"), "events", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)
    op.create_index(op.f("ix_events_source_id"), "events", ["source_id"], unique=False)
    op.create_index(op.f("ix_events_venue_id"), "events", ["venue_id"], unique=False)
    op.create_table(
        "event_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "category_id", name="uq_event_category"),
    )
    op.create_index(
        op.f("ix_event_categories_category_id"),
        "event_categories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_categories_event_id"),
        "event_categories",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "event_occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("start_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_occurrences_event_id"),
        "event_occurrences",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_occurrences_start_datetime_utc"),
        "event_occurrences",
        ["start_datetime_utc"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_occurrences_start_datetime_utc"), table_name="event_occurrences"
    )
    op.drop_index(op.f("ix_event_occurrences_event_id"), table_name="event_occurrences")
    op.drop_table("event_occurrences")
    op.drop_index(op.f("ix_event_categories_event_id"), table_name="event_categories")
    op.drop_index(
        op.f("ix_event_categories_category_id"), table_name="event_categories"
    )
    op.drop_table("event_categories")
    op.drop_index(op.f("ix_events_venue_id"), table_name="events")
    op.drop_index(op.f("ix_events_source_id"), table_name="events")
    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_index(op.f("ix_events_external_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_venues_slug"), table_name="venues")
    op.drop_table("venues")
    op.drop_table("sources")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
